In [9]:
import numpy as np

In [10]:
np.random.randint(1,[3,50,100], size=(5,3))

array([[ 1,  6, 55],
       [ 1, 34, 40],
       [ 2, 22,  4],
       [ 2,  4,  9],
       [ 2, 24, 98]])

In [11]:
np.random.randint(1,[3,50,100], (5,3))

array([[ 1, 18, 10],
       [ 1, 25, 85],
       [ 1, 30, 75],
       [ 1,  2,  9],
       [ 2, 48, 92]])

In [12]:
np.random.randint([1,3,4,19], 20, (5,4))

array([[14,  8, 16, 19],
       [ 6, 18, 18, 19],
       [17,  9, 16, 19],
       [11, 12, 11, 19],
       [ 4,  4, 14, 19]])

In [13]:
a=np.random.randint(10,size=10)

In [14]:
a.dtype

dtype('int64')

In [15]:
b=np.full((4,6),2.2)

In [16]:
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [17]:
b.dtype

dtype('float64')

In [18]:
a=np.array([2,3,4,5])
np.split(a, 2)

[array([2, 3]), array([4, 5])]

In [19]:
m=np.arange(20).reshape(5,4)

In [20]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
np.split(m,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [24]:
m=np.arange(20).reshape(5,4)

np.vsplit(m,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [25]:
twoD=np.random.randint(5,100, (3,3))
twoD

array([[35, 15, 95],
       [92, 79, 58],
       [73, 34, 31]])

In [28]:
y=np.sort(twoD, axis=0)

In [27]:
twoD

array([[35, 15, 95],
       [92, 79, 58],
       [73, 34, 31]])

In [29]:
y

array([[35, 15, 31],
       [73, 34, 58],
       [92, 79, 95]])

In [30]:
np.sort(twoD, axis=1)

array([[15, 35, 95],
       [58, 79, 92],
       [31, 34, 73]])

In [31]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[0,2]

15

In [34]:
arr_2d[2][0]

35

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
(arr_2d[:2])[1:]

array([[20, 25, 30]])

In [40]:
jj=np.arange(1,17).reshape(4,4)

In [41]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
jj[[1,2], [0,3]]

array([ 5, 12])

In [44]:
jj[0:,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [45]:
jj[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [48]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [49]:
ss=np.arange(1,13)

In [50]:
ss

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
ss[(ss%3==0)&(ss>4)]

array([ 6,  9, 12])