In [1]:
import numpy as np

In [2]:
np.random.randint(1,[3,50,100], size=(5,3))

array([[ 1, 19, 91],
       [ 2, 10, 50],
       [ 2, 14, 81],
       [ 1, 34, 34],
       [ 2, 41,  6]])

In [3]:
np.random.randint(1,[3,50,100], (5,3))

array([[ 2, 23, 41],
       [ 2, 44, 50],
       [ 1, 13, 75],
       [ 2, 13, 36],
       [ 1, 10, 67]])

In [7]:
np.random.randint([1,3,4,19], 20, (5,4))

array([[14, 14, 10, 19],
       [12, 13, 17, 19],
       [18, 13,  8, 19],
       [10,  7,  6, 19],
       [17, 10,  8, 19]])

In [8]:
a=np.random.randint(10,size=10)

In [9]:
a.dtype

dtype('int64')

In [10]:
b=np.full((4,6),2.2)

In [11]:
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [12]:
b.dtype

dtype('float64')

In [13]:
a=np.array([2,3,4,5])
np.split(a, 2)

[array([2, 3]), array([4, 5])]

In [14]:
m=np.arange(20).reshape(5,4)

In [15]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
np.split(m,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]