# Numpy

In [2]:
# numpy.array(list)
# numpy.arrange()

In [3]:
import numpy as np

# array

In [4]:
np.array([2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
my_list = [2,5,7,9,12,6,4,10,12]
my_list

[2, 5, 7, 9, 12, 6, 4, 10, 12]

In [7]:
np.array(my_list)

array([ 2,  5,  7,  9, 12,  6,  4, 10, 12])

In [8]:
np.random.randint(0,1001,10)

array([185, 987, 938, 655, 907, 737, 277, 277, 632, 460])

# arange 

In [9]:
np.arange(3,11,1)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# zeros

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# eye

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# full

In [15]:
np.full(5,10)

array([10, 10, 10, 10, 10])

# linspace

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [18]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# random

In [20]:
from numpy import random

In [21]:
import numpy as np

In [22]:
np.random.rand(2)

array([0.1610886 , 0.58712414])

In [23]:
np.random.rand(20)

array([0.63213828, 0.86332091, 0.49273976, 0.42390116, 0.1384881 ,
       0.78144832, 0.39904684, 0.66285861, 0.76232271, 0.85781808,
       0.07246094, 0.65856709, 0.67765371, 0.67018605, 0.98805785,
       0.89279883, 0.38603332, 0.05583114, 0.94042313, 0.17572506])

In [24]:
np.random.rand(5,5)

array([[0.15535566, 0.0159797 , 0.67328554, 0.5659653 , 0.42557396],
       [0.63989918, 0.69689267, 0.14275349, 0.3150444 , 0.57488288],
       [0.68957541, 0.05986445, 0.46152761, 0.51217117, 0.12295196],
       [0.14648765, 0.42103923, 0.86620944, 0.1407779 , 0.1670866 ],
       [0.37807709, 0.30701529, 0.6038051 , 0.00998393, 0.30084737]])

In [25]:
np.random.randn(5)

array([ 0.06778173,  1.75682936, -2.27698076,  0.11790001,  1.38142677])

In [26]:
np.random.randn(5,10)

array([[-0.26021225, -0.26175151,  0.90125123, -0.42066873,  1.22621437,
         1.24278   , -1.16322655,  0.47684819,  0.96823185,  0.05676237],
       [ 1.46440604,  0.4615345 , -0.44829528, -0.35791528, -0.02055403,
         0.40995473,  1.03518983, -0.81590982, -0.23865581,  0.15368804],
       [ 0.30651693, -0.31353794,  0.0162227 ,  0.16009439, -0.95455786,
        -0.70170092,  0.02684147, -1.74202173,  0.93401225, -0.82784517],
       [-0.4332289 ,  2.41358097,  0.76108134,  0.78327345,  0.33332284,
         0.59937416,  0.06676727,  0.42852391, -0.65802939, -1.50965565],
       [ 1.01421484, -0.39407359,  0.36163664,  2.5319785 , -0.51560736,
        -1.10461415,  1.34253381,  0.11514301,  0.07072047, -0.02544436]])

In [27]:
np.random.randint(1,50,12)

array([20,  2,  9, 45, 16, 42, 24, 38, 36, 20,  5, 20])

In [28]:
np.random.randint(1,100)

10

In [29]:
np.random.randint(1,100, size =5 )

array([ 7, 43, 27, 51, 54])

In [30]:
np.random.randint(5, size =10)

array([0, 1, 2, 3, 2, 4, 4, 0, 1, 1])

# reshape

In [31]:
arr = np.arange(25)
arrarr = np.random.randint(0,50,10)

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arrarr.reshape(2,5)

array([[ 5, 35, 38, 30, 45],
       [ 8, 41, 15, 33, 16]])

# min max argmax argmin

In [34]:
arrarr.max()

45

In [35]:
arrarr.argmax()

4

In [36]:
arrarr.min()

5

In [37]:
arrarr.argmin()

0

# shape

In [38]:
arr.shape

(25,)

In [39]:
arr.reshape(25,1).shape

(25, 1)

# ndim

In [40]:
arr = np.arange(1,10)

In [41]:
arr.ndim

1

In [42]:
arr1 = np.arange(1,11).reshape(2,5)

In [43]:
arr1.ndim

2

# size 

In [44]:
arr2 = np.random.randint(1,50,13)

In [45]:
arr2.size

13

In [46]:
arr3 = np.random.randint(1,50,15).reshape(3,5)

In [47]:
arr3.size

15

# concatenate

In [48]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [49]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [50]:
np.concatenate([x,y]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
z = np.array([7,8,9])

In [52]:
np.concatenate([x,y,z]).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# spliting of array

In [53]:
x = np.array([3,5,9,2,3,7,8,0,5,7,1,2])

In [54]:
np.split(x, [3,5])

[array([3, 5, 9]), array([2, 3]), array([7, 8, 0, 5, 7, 1, 2])]

In [55]:
a, b, c = np.split(x, [3,5])

In [56]:
a

array([3, 5, 9])

In [57]:
b

array([2, 3])

In [58]:
c

array([7, 8, 0, 5, 7, 1, 2])

In [59]:
np.split(x,4)

[array([3, 5, 9]), array([2, 3, 7]), array([8, 0, 5]), array([7, 1, 2])]

In [60]:
m = np.arange(20).reshape(5,4)

In [61]:
np.split(m,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [62]:
np.split(m,[1,3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [63]:
np.vsplit(m,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [64]:
upper, lower = np.split(m,[3])

In [65]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
np.vsplit(m,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [68]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

# sorting of arrays

In [74]:
v = np.array([2,5,3,7,8,1,4,6])

In [75]:
np.sort(v)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
v.sort()

In [77]:
v

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
z = np.random.randint(1,100,(3,3))

In [86]:
z

array([[98, 36, 70],
       [ 2, 66, 88],
       [31, 59, 93]])

In [87]:
np.sort(z,axis=0)

array([[ 2, 36, 70],
       [31, 59, 88],
       [98, 66, 93]])

In [88]:
np.sort(z,axis=1)

array([[36, 70, 98],
       [ 2, 66, 88],
       [31, 59, 93]])

# Numpy Index

In [93]:
arr = np.arange(11)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr[8]

8

In [96]:
arr[-1]

10

In [97]:
arr[3:7]

array([3, 4, 5, 6])

In [98]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [99]:
arr[3:7]=100

In [100]:
arr

array([  0,   1,   2, 100, 100, 100, 100,   7,   8,   9,  10])

In [101]:
arr[:5]=100

In [102]:
arr

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10])

In [103]:
arr[1::2]

array([100, 100, 100,   7,   9])

In [104]:
arr[::2]

array([100, 100, 100, 100,   8,  10])

In [105]:
arr2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [106]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [107]:
arr2d[1]

array([20, 25, 30])

In [108]:
arr2d[1][0]

20

In [109]:
arr2d[1,0]

20

In [111]:
arr2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [115]:
arr2d[:,1:2]

array([[10],
       [25],
       [40]])

In [116]:
arr2d[1,1]

25

In [117]:
aa = np.arange(0,30,3)

In [118]:
index =[3,6,9]

In [119]:
aa[index]

array([ 9, 18, 27])